development:
  clients:
    default:
      database: mongo_app_development
      hosts:
        - localhost:27017
      options:

  options:

test:
  clients:
    default:
      database: mongo_app_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      database: mongo_app_production
      hosts:
        - localhost:27017
      options:

  options:
